djangocms_blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf.urls import url

from .feeds import FBInstantArticles, LatestEntriesFeed, TagFeed
from .settings import get_setting
from .views import (
    AuthorEntriesView, CategoryEntriesView, PostArchiveView, PostDetailView, PostListView,
    TaggedListView,
)


def get_urls():
    urls = get_setting('PERMALINK_URLS')
    details = []
    for urlconf in urls.values():
        details.append(
            url(urlconf, PostDetailView.as_view(), name='post-detail'),
        )
    return details


detail_urls = get_urls()

urlpatterns = [
    url(r'^$',
        PostListView.as_view(), name='posts-latest'),
    url(r'^feed/$',
        LatestEntriesFeed(), name='posts-latest-feed'),
    url(r'^feed/fb/$',
        FBInstantArticles(), name='posts-latest-feed-fb'),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveView.as_view(), name='posts-archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        PostArchiveView.as_view(), name='posts-archive'),
    url(r'^author/(?P<username>[\w\.@+-]+)/$',
        AuthorEntriesView.as_view(), name='posts-author'),
    url(r'^category/(?P<category>[\w\.@+-]+)/$',
        CategoryEntriesView.as_view(), name='posts-category'),
    url(r'^tag/(?P<tag>[-\w]+)/$',
        TaggedListView.as_view(), name='posts-tagged'),
    url(r'^tag/(?P<tag>[-\w]+)/feed/$',
        TagFeed(), name='posts-tagged-feed'),
] + detail_urls

djangosite/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from des import urls as des_urls
#from machina.app import board
from cms import views as cms_views
from django.urls import LocaleRegexURLResolver, get_resolver
def _patch_lang_pfx():
    for url_pattern in get_resolver(None).url_patterns:
        if isinstance(url_pattern, LocaleRegexURLResolver):
            return url_pattern.prefix_default_language
    return False
# Swap out the faulty method from cms.views
cms_views.is_language_prefix_patterns_used = _patch_lang_pfx


admin.autodiscover()

urlpatterns = [
    url(r'^django-des/', include(des_urls)),
    #url(r'^catalog/', include('sitecatalog.urls')),
    #url(r'^accounts/', include('allauth.urls')),
    #url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    #url(r'^forum/', include(board.urls)),
    url(r'^', include('djangocms_forms.urls')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^', include('cms.urls')),
    prefix_default_language=False,
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

djangocms_blog/liveblog/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

import json
from operator import itemgetter

import django
from channels import Group
from cms.models import CMSPlugin
from cms.utils.plugins import reorder_plugins
from django.db import models
from django.template import Context
from django.utils.six import python_2_unicode_compatible
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from djangocms_text_ckeditor.models import AbstractText
from filer.fields.image import FilerImageField

from djangocms_blog.models import Post, thumbnail_model
from djangocms_blog.settings import DATE_FORMAT


@python_2_unicode_compatible
class LiveblogInterface(models.Model):
    """
    Abstract Liveblog plugin model, reusable to customize the liveblogging
    plugins.

    When implementing this, you **must** call ``self._post_save()`` in the
    concrete plugin model ``save`` method.
    """
    publish = models.BooleanField(_('publish liveblog entry'), default=False)
    post_date = models.DateTimeField(_('post date'), blank=True, default=now)

    class Meta:
        verbose_name = _('liveblog entry')
        verbose_name_plural = _('liveblog entries')
        abstract = True

    def __str__(self):
        return str(self.pk)

    def _post_save(self):
        """
        Reorder plugins according to the post_date value. All (and only)
        subclasses of LiveblogInterface are taken into consideration and
        reordered together
        """
        items = []
        for model in LiveblogInterface.__subclasses__():
            items.extend(
                model.objects.filter(placeholder=self.placeholder).values('pk', 'post_date')
            )
        order = reversed([item['pk'] for item in sorted(items, key=itemgetter('post_date'))])
        reorder_plugins(self.placeholder, None, self.language, order)

    @property
    def liveblog_group(self):
        post = Post.objects.language(self.language).filter(liveblog=self.placeholder).first()
        if post:
            return post.liveblog_group

    def render(self, request):
        context = Context({
            'request': request
        })
        try:
            from cms.plugin_rendering import ContentRenderer
            renderer = ContentRenderer(request)
            return renderer.render_plugin(
                instance=self,
                context=context,
                placeholder=self.placeholder,
            )
        except ImportError:
            return self.render_plugin(context)

    def send(self, request):
        """
        Render the content and send to the related group
        """
        if self.liveblog_group:
            notification = {
                'id': self.pk,
                'content': self.render(request),
                'creation_date': self.post_date.strftime(DATE_FORMAT),
                'changed_date': self.changed_date.strftime(DATE_FORMAT),
            }
            Group(self.liveblog_group).send({
                'text': json.dumps(notification),
            })


class Liveblog(LiveblogInterface, AbstractText):
    """
    Basic liveblog plugin model
    """
    if django.VERSION >= (1, 10):
        cmsplugin_ptr = models.OneToOneField(
            CMSPlugin,
            related_name='%(app_label)s_%(class)s', primary_key=True,
            parent_link=True, on_delete=models.CASCADE
        )
    title = models.CharField(_('title'), max_length=255)
    image = FilerImageField(
        verbose_name=_('image'), blank=True, null=True, on_delete=models.SET_NULL,
        related_name='djangocms_blog_liveblog_image'
    )
    thumbnail = models.ForeignKey(
        thumbnail_model, verbose_name=_('thumbnail size'), on_delete=models.SET_NULL,
        blank=True, null=True, related_name='djangocms_blog_liveblog_thumbnail'
    )

    class Meta:
        verbose_name = _('liveblog entry')
        verbose_name_plural = _('liveblog entries')

    def save(self, *args, **kwargs):
        super(Liveblog, self).save(*args, **kwargs)
        self._post_save()

    def __str__(self):
        return AbstractText.__str__(self)

djangocms_blog/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

import hashlib

from aldryn_apphooks_config.fields import AppHookConfigField
from aldryn_apphooks_config.managers.parler import AppHookConfigTranslatableManager
from cms.models import CMSPlugin, PlaceholderField
from django.conf import settings as dj_settings
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.utils import timezone
from django.utils.encoding import force_bytes, force_text, python_2_unicode_compatible
from django.utils.functional import cached_property
from django.utils.html import escape, strip_tags
from django.utils.translation import get_language, ugettext, ugettext_lazy as _
from djangocms_text_ckeditor.fields import HTMLField
from filer.fields.image import FilerImageField
from meta.models import ModelMeta
from parler.models import TranslatableModel, TranslatedFields
from parler.utils.context import switch_language
from sortedm2m.fields import SortedManyToManyField
from taggit_autosuggest.managers import TaggableManager

from .cms_appconfig import BlogConfig
from .fields import AutoSlugField, slugify
from .managers import GenericDateTaggedManager
from .settings import get_setting

BLOG_CURRENT_POST_IDENTIFIER = get_setting('CURRENT_POST_IDENTIFIER')
BLOG_CURRENT_NAMESPACE = get_setting('CURRENT_NAMESPACE')
BLOG_PLUGIN_TEMPLATE_FOLDERS = get_setting('PLUGIN_TEMPLATE_FOLDERS')

try:  # pragma: no cover
    from cmsplugin_filer_image.models import ThumbnailOption  # NOQA
except ImportError:  # pragma: no cover
    from filer.models import ThumbnailOption  # NOQA

thumbnail_model = '%s.%s' % (
    ThumbnailOption._meta.app_label, ThumbnailOption.__name__
)

try:
    from knocker.mixins import KnockerModel
except ImportError:
    class KnockerModel(object):
        """
        Stub class if django-knocker is not installed
        """
        pass


class BlogMetaMixin(ModelMeta):

    def get_meta_attribute(self, param):
        """
        Retrieves django-meta attributes from apphook config instance
        :param param: django-meta attribute passed as key
        """
        return self._get_meta_value(param, getattr(self.app_config, param)) or ''

    def get_locale(self):
        return self.get_current_language()

    def get_full_url(self):
        """
        Return the url with protocol and domain url
        """
        return self.build_absolute_uri(self.get_absolute_url())


@python_2_unicode_compatible
class BlogCategory(BlogMetaMixin, TranslatableModel):
    """
    Blog category
    """
    parent = models.ForeignKey(
        'self', verbose_name=_('parent'), null=True, blank=True, related_name='children'
    )
    date_created = models.DateTimeField(_('created at'), auto_now_add=True)
    date_modified = models.DateTimeField(_('modified at'), auto_now=True)
    app_config = AppHookConfigField(
        BlogConfig, null=True, verbose_name=_('app. config')
    )

    translations = TranslatedFields(
        name=models.CharField(_('name'), max_length=767),
        slug=models.SlugField(_('slug'), max_length=767, blank=True, db_index=True),
        meta_description=models.TextField(
            verbose_name=_('category meta description'), blank=True, default=''
        ),
        meta={'unique_together': (('language_code', 'slug'),)}
    )

    objects = AppHookConfigTranslatableManager()

    _metadata = {
        'title': 'get_title',
        'description': 'get_description',
        'og_description': 'get_description',
        'twitter_description': 'get_description',
        'gplus_description': 'get_description',
        'locale': 'get_locale',
        'object_type': 'get_meta_attribute',
        'og_type': 'get_meta_attribute',
        'og_app_id': 'get_meta_attribute',
        'og_profile_id': 'get_meta_attribute',
        'og_publisher': 'get_meta_attribute',
        'og_author_url': 'get_meta_attribute',
        'og_author': 'get_meta_attribute',
        'twitter_type': 'get_meta_attribute',
        'twitter_site': 'get_meta_attribute',
        'twitter_author': 'get_meta_attribute',
        'gplus_type': 'get_meta_attribute',
        'gplus_author': 'get_meta_attribute',
        'url': 'get_absolute_url',
    }

    class Meta:
        verbose_name = _('blog category')
        verbose_name_plural = _('blog categories')

    def descendants(self):
        children = []
        if self.children.exists():
            children.extend(self.children.all())
            for child in self.children.all():
                children.extend(child.descendants())
        return children

    @cached_property
    def linked_posts(self):
        return self.blog_posts.namespace(self.app_config.namespace)

    @cached_property
    def count(self):
        return self.linked_posts.published().count()

    @cached_property
    def count_all_sites(self):
        return self.linked_posts.published(current_site=False).count()

    def get_absolute_url(self, lang=None):
        if not lang or lang not in self.get_available_languages():
            lang = get_language()
        if not lang or lang not in self.get_available_languages():
            lang = self.get_current_language()
        if self.has_translation(lang):
            slug = self.safe_translation_getter('slug', language_code=lang)
            return reverse(
                '%s:posts-category' % self.app_config.namespace,
                kwargs={'category': slug},
                current_app=self.app_config.namespace
            )
        # in case category doesn't exist in this language, gracefully fallback
        # to posts-latest
        return reverse(
            '%s:posts-latest' % self.app_config.namespace, current_app=self.app_config.namespace
        )

    def __str__(self):
        default = ugettext('BlogCategory (no translation)')
        return self.safe_translation_getter('name', any_language=True, default=default)

    def save(self, *args, **kwargs):
        super(BlogCategory, self).save(*args, **kwargs)
        for lang in self.get_available_languages():
            self.set_current_language(lang)
            if not self.slug and self.name:
                self.slug = slugify(force_text(self.name))
        self.save_translations()

    def get_title(self):
        title = self.safe_translation_getter('name', any_language=True)
        return title.strip()

    def get_description(self):
        description = self.safe_translation_getter('meta_description', any_language=True)
        return escape(strip_tags(description)).strip()


@python_2_unicode_compatible
class Post(KnockerModel, BlogMetaMixin, TranslatableModel):
    """
    Blog post
    """
    author = models.ForeignKey(dj_settings.AUTH_USER_MODEL,
                               verbose_name=_('author'), null=True, blank=True,
                               related_name='djangocms_blog_post_author')

    date_created = models.DateTimeField(_('created'), auto_now_add=True)
    date_modified = models.DateTimeField(_('last modified'), auto_now=True)
    date_published = models.DateTimeField(_('published since'), null=True, blank=True)
    date_published_end = models.DateTimeField(_('published until'), null=True, blank=True)
    date_featured = models.DateTimeField(_('featured date'), null=True, blank=True)
    publish = models.BooleanField(_('publish'), default=False)
    categories = models.ManyToManyField('djangocms_blog.BlogCategory', verbose_name=_('category'),
                                        related_name='blog_posts', blank=True)
    main_image = FilerImageField(verbose_name=_('main image'), blank=True, null=True,
                                 on_delete=models.SET_NULL,
                                 related_name='djangocms_blog_post_image')
    main_image_thumbnail = models.ForeignKey(thumbnail_model,
                                             verbose_name=_('main image thumbnail'),
                                             related_name='djangocms_blog_post_thumbnail',
                                             on_delete=models.SET_NULL,
                                             blank=True, null=True)
    main_image_full = models.ForeignKey(thumbnail_model,
                                        verbose_name=_('main image full'),
                                        related_name='djangocms_blog_post_full',
                                        on_delete=models.SET_NULL,
                                        blank=True, null=True)
    enable_comments = models.BooleanField(verbose_name=_('enable comments on post'),
                                          default=get_setting('ENABLE_COMMENTS'))
    sites = models.ManyToManyField('sites.Site', verbose_name=_('Site(s)'), blank=True,
                                   help_text=_('Select sites in which to show the post. '
                                               'If none is set it will be '
                                               'visible in all the configured sites.'))
    app_config = AppHookConfigField(
        BlogConfig, null=True, verbose_name=_('app. config')
    )

    translations = TranslatedFields(
        title=models.CharField(_('title'), max_length=767),
        slug=AutoSlugField(_('slug'), max_length=767, blank=True,
                           db_index=True, allow_unicode=True),
        subtitle=models.CharField(verbose_name=_('subtitle'), max_length=767,
                                  blank=True, default=''),
        abstract=HTMLField(_('abstract'), blank=True, default='',
                           configuration='BLOG_ABSTRACT_CKEDITOR'),
        meta_description=models.TextField(verbose_name=_('post meta description'),

djangocms_blog/templates/djangocms_blog/base.html
{% extends CMS_TEMPLATE %}

{% block meta %}
    {%  if meta %}
        {% include "meta/meta.html" %}
    {% endif %}
{% endblock meta %}

{% block content %}
<div class="app app-blog">
    {% block content_blog %}{% endblock %}
</div>
{% endblock content %}

djangocms_blog/templates/djangocms_blog/post_archive.html
{% extends "djangocms_blog/post_list.html" %}

djangocms_blog/templates/djangocms_blog/post_detail.html
{% extends "djangocms_blog/base.html" %}
{% load i18n easy_thumbnails_tags cms_tags %}

{% block canonical_url %}<link rel="canonical" href="{{ meta.url }}"/>{% endblock canonical_url %}
{% block title %}{{ post.get_title }}{% endblock %}

{% block content_blog %}{% spaceless %}
<article id="post-{{ post.slug }}" class="post-item post-detail">
    <header>
        <h2>{% render_model post "title" %}</h2>
        {% if post.subtitle %}
            <h3>{% render_model post "subtitle" %}</h3>
        {% endif %}
        {% block blog_meta %}
            {% include "djangocms_blog/includes/blog_meta.html" %}
        {% endblock %}
    </header>
    {% if post.main_image_id %}
    <div class="blog-visual">
        {% thumbnail post.main_image post.full_image_options.size crop=post.full_image_options.crop upscale=post.full_image_options.upscale subject_location=post.main_image.subject_location  as thumb %}
        <img src="{{ thumb.url }}" alt="{{ post.main_image.default_alt_text }}" width="{{ thumb.width }}" height="{{ thumb.height }}" />
    </div>
    {% endif %}
    {% endspaceless %}
    {% if post.app_config.use_placeholder %}
        <div class="blog-content">{% render_placeholder post.content %}</div>
    {% else %}
        <div class="blog-content">{% render_model post "post_text" "post_text" "" "safe" %}</div>
    {% endif %}
    {% if view.liveblog_enabled %}
        {% include "liveblog/includes/post_detail.html" %}
    {% endif %}
    {% if post.related.exists %}
        <section class="post-detail-list">
        {% for related in post.related.all %}
            {% include "djangocms_blog/includes/blog_item.html" with post=related image="true" TRUNCWORDS_COUNT=TRUNCWORDS_COUNT %}
        {% endfor %}
        </section>
    {% endif %}
</article>
{% endblock content_blog %}

djangocms_blog/templates/djangocms_blog/post_instant_article.html
{% load easy_thumbnails_tags cms_tags %}
<!doctype html>
<html lang="{{ post.get_current_language }}" prefix="op: http://media.facebook.com/op#">
  <head>
    <meta charset="utf-8">
    {% block canonical_url %}<link rel="canonical" href="{{ meta.url }}"/>{% endblock canonical_url %}
    <meta property="op:markup_version" content="v1.0">
  </head>
  <body>
    <article>
      <header>
        <h1>{{ post.title }}</h1>
        {% if post.subtitle %}
            <h2>{{ post.subtitle }}</h2>
        {% endif %}
        <time class="op-published" datetime="{{ post.date_published|date:"Y-m-d\TH:i:sO" }}">{{ post.date_published|date:"DATE_FORMAT" }}</time>
        <time class="op-modified" dateTime="{{ post.date_modified|date:"Y-m-d\TH:i:sO" }}">{{ post.date_modified|date:"DATE_FORMAT" }}</time>
        <address>
            <a {% if og_author_url %}rel="facebook" href="{{ og_author_url }}"{% endif %}>{{ post.get_author_name }}</a>
        </address>
        <figure>
            <img src="{{ meta.image }}" alt="{{ post.main_image.default_alt_text|default:'' }}" />
            {% if post.main_image.default_caption %}<figcaption>{{ post.main_image.default_caption }}</figcaption>{% endif %}
        </figure>
        <h3 class="op-kicker">{{ post.abstract|striptags|safe }}</h3>
      </header>
      {% if post.app_config.use_placeholder %}
      <div class="blog-content">{% render_placeholder post.content %}</div>
      {% else %}
      <div class="blog-content">{% render_model post "post_text" "post_text" "" "safe" %}</div>
      {% endif %}
    </article>
  </body>
</html>

djangocms_blog/templates/djangocms_blog/post_list.html
{% extends "djangocms_blog/base.html" %}
{% load i18n easy_thumbnails_tags %}{% spaceless %}

{% block canonical_url %}<link rel="canonical" href="{{ view.get_view_url }}"/>{% endblock canonical_url %}

{% block content_blog %}
<section class="blog-list">
    {% block blog_title %}
    <header>
        <h2>
        {% if author %}{% trans "Articles by" %} {{ author.get_full_name }}
        {% elif archive_date %}{% trans "Archive" %} &ndash; {% if month %}{{ archive_date|date:'F' }} {% endif %}{{ year }}
        {% elif tagged_entries %}{% trans "Tag" %} &ndash; {{ tagged_entries|capfirst }}
        {% elif category %}{% trans "Category" %} &ndash; {{ category }}{% endif %}
        </h2>
    </header>
    {% endblock %}
    {% for post in post_list %}
        {% include "djangocms_blog/includes/blog_item.html" with post=post image="true" TRUNCWORDS_COUNT=TRUNCWORDS_COUNT %}
    {% empty %}
    <p class="blog-empty">{% trans "No article found." %}</p>
    {% endfor %}
    {% if author or archive_date or tagged_entries %}
    <p class="blog-back"><a href="{% url 'djangocms_blog:posts-latest' %}">{% trans "Back" %}</a></p>
    {% endif %}
    {% if is_paginated %}
    <nav class="{% firstof css_grid instance.css_grid %} pagination">
        {% if page_obj.has_previous %}
            <a href="?{{ view.page_kwarg }}={{ page_obj.previous_page_number }}">&laquo; {% trans "previous" %}</a>
        {% endif %}
        <span class="current">
            {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
            <a href="?{{ view.page_kwarg }}={{ page_obj.next_page_number }}">{% trans "next" %} &raquo;</a>
        {% endif %}
    </nav>
    {% endif %}
</section>
{% endblock %}
{% endspaceless %}